name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gofmt:
    uses: Jerome1337/gofmt-action@v1.0.5
    with:
      gofmt-path: '.'

  dockerize:
    uses: GEWIS/actions/.github/workflows/docker-build.yml@v1
    with:
      projects: '["."]'