name: Semantic release

on:
  push:
    branches:
      - master

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@v1

  release-server:
    uses: GEWIS/actions/.github/workflows/docker-release-ghcr.yml@v1.9.0
    needs: versioning
    if: ${{ needs.versioning.outputs.next-version != '' }}
    with:
      projects: "['.']"
      version: ${{ needs.versioning.outputs.next-version }}
      docker-paths: "['gewis/radio/backend']"

